#!/usr/bin/expect

# Set the admin password to 'changethispassword'
# Xavier Gandillot <xavier@gandillot.com>
# 24/09/2014

spawn ./asadmin --user admin change-admin-password
expect "password" 
send "\n" 
expect "password"
send "changethispassword\n"
expect "password"
send "changethispassword\n"
expect eof 
exit
